/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageEnlargedFrameView.java
 *
 * Created on Jan 8, 2010, 12:59:10 PM
 */

package maggi_1;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author tomer
 */
public class ImageEnlargedFrameView extends javax.swing.JFrame {

    JLabel label_image = new JLabel();
    /** Creates new form ImageEnlargedFrameView */
    public ImageEnlargedFrameView() {
        initComponents();
    }

    @SuppressWarnings("static-access")
    public ImageEnlargedFrameView(int val){
        
        initComponents();

        this.setSize(Main.popupcontrol.popupview.getWidth()/2 + 35,Main.popupcontrol.popupview.getHeight());
        label_image.setSize(this.getWidth(),this.getHeight());

        ImageIcon imgicon = new ImageIcon(Main.popupcontrol.popupview.folderpath_popupview + val + ".jpg");
        Image img = imgicon.getImage();

        imgicon.setImage(img.getScaledInstance(label_image.getWidth(),label_image.getHeight(),Image.SCALE_SMOOTH));

        label_image.setIcon(imgicon);

        getContentPane().add(label_image,new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageEnlargedFrameView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
