/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SplashView.java
 *
 * Created on Jan 19, 2010, 8:41:02 PM
 */

package maggi_1;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;


/**
 *
 * @author Toshish
 */
public class SplashView extends javax.swing.JFrame {

    Timer timer_splash;
    /** Creates new form SplashView */
    public SplashView() {

        initComponents();

        ImageIcon imgicon =  new ImageIcon(Main.curdir + "/src/maggi_1/icons/maggi_splash.JPG");
        Image img = imgicon.getImage();
        imgicon.setImage(img.getScaledInstance(label_image2.getWidth(),label_image2.getHeight(),Image.SCALE_SMOOTH));
    
        label_image2.setIcon(imgicon);


        setLocation( (int) Main.screensize.getWidth()/2 - (int) getWidth()/2,(int) Main.screensize.getHeight()/2 - (int) getHeight()/2);

        timer_splash = new Timer(200,new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if(Main.startupdone){
                    timer_splash.stop();
                    Main.splashview.dispose();                    
                }
                else{
                    progressbar_splash.setValue(progressbar_splash.getValue() + 1);
                }
            }
        });
        
        timer_splash.start();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressbar_splash = new javax.swing.JProgressBar();
        panel_about = new javax.swing.JPanel();
        label_image1 = new javax.swing.JLabel();
        label_image2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressbar_splash.setForeground(new java.awt.Color(57, 125, 206));
        progressbar_splash.setMinimum(30);
        getContentPane().add(progressbar_splash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 620, 20));

        panel_about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maggi_1/icons/chinese_food_box_noodles_hanging_md_wht.gif"))); // NOI18N
        panel_about.add(label_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 120));
        panel_about.add(label_image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 310));

        getContentPane().add(panel_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_image1;
    private javax.swing.JLabel label_image2;
    private javax.swing.JPanel panel_about;
    private javax.swing.JProgressBar progressbar_splash;
    // End of variables declaration//GEN-END:variables

}
