/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TimeLineTextInfoView.java
 *
 * Created on 13 Jan, 2010, 5:09:01 PM
 */

/**
 *
 * @author toshish
 */
package maggi_1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

public class TimeLineTextInfoView extends javax.swing.JFrame {

    /** Creates new form TimeLineTextInfoView */
    public TimeLineTextInfoView() {
        initComponents();
        initButtonListener();
    }

    void initButtonListener(){
        btn_close.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                setVisible(false);
            }
        });
    }

    public void setData(Timestamp datetime,int xPos,int yPos){


        DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        
        try{
            Statement st = Main.con.createStatement();
            ResultSet rs = st.executeQuery("select textline,l1id,l2id from POPUP where datetime='"+df.format(datetime)+"'");
            rs.next();
            textarea_textinfo.setText(rs.getString("textline"));
            rs = st.executeQuery("select subtopic from L2 where l1id="+rs.getInt("l1id")+" and l2id="+rs.getInt("l2id"));
            rs.next();
            label_SubTopic.setText(rs.getString("subtopic"));
        }
        catch(SQLException ex){
            System.out.println("SQLException in setData()::" + ex.getMessage());
        }
        finally{
            setBounds(xPos,yPos,getWidth(),getHeight());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpane_textinfoview = new javax.swing.JScrollPane();
        textarea_textinfo = new javax.swing.JTextArea();
        label_SubTopic = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textarea_textinfo.setBackground(new java.awt.Color(255, 255, 204));
        textarea_textinfo.setColumns(20);
        textarea_textinfo.setEditable(false);
        textarea_textinfo.setLineWrap(true);
        textarea_textinfo.setRows(5);
        textarea_textinfo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        scrollpane_textinfoview.setViewportView(textarea_textinfo);

        getContentPane().add(scrollpane_textinfoview, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 108));

        label_SubTopic.setText("jLabel1");
        getContentPane().add(label_SubTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 20));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maggi_1/icons/close.png"))); // NOI18N
        btn_close.setBorder(null);
        btn_close.setContentAreaFilled(false);
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 20, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeLineTextInfoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel label_SubTopic;
    private javax.swing.JScrollPane scrollpane_textinfoview;
    private javax.swing.JTextArea textarea_textinfo;
    // End of variables declaration//GEN-END:variables

}
