/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutDialog.java
 *
 * Created on 15 Jan, 2010, 7:21:06 PM
 */

package maggi_1;

import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author toshish
 */
public class AboutDialog extends javax.swing.JFrame {

    /** Creates new form AboutDialog */
    public AboutDialog() {
        initComponents();

        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent we){
                Main.about_us.dispose();
                Main.about_us = null;
            }
        });

        ImageIcon imgico = new ImageIcon(Main.curdir + "/src/maggi_1/icons/maggi_splash.JPG");
        Image img = imgico.getImage();
        imgico.setImage(img.getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH));
        jLabelImage.setIcon(imgico);
        jLabel2.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Maggi Learning");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setText("<html>Developed by:<br> Anirudh Tomer (anirudhtomer@gmail.com)<br> Toshish Jawale (jawaletoshish@gmail.com) <br> Gaurav Deshmukh (gaurav.gk71189@gmail.com) <br> As a project for <b>Amdocs Innovation Lab in MIT, Pune.</b>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 470, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 500, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maggi_1/icons/chinese_food_box_noodles_hanging_md_wht.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 90));

        jLabelImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
